CREATE TABLE [dbo].[UserSettings]
(
	[Username] NVARCHAR(50) NOT NULL, 
    [ColorNewItem] NVARCHAR(10) NOT NULL DEFAULT '#FFF5F533', 
    [ColorChequeSoldItemColor] NVARCHAR(10) NOT NULL DEFAULT '#ff66e6ff', 
    [ColorChequeNonSufficientFundItem] NVARCHAR(10) NOT NULL DEFAULT '#ffff9c7a', 
    [ColorChequeCashedItem] NVARCHAR(10) NOT NULL DEFAULT '#ff94ffb6', 
    [ColorChequeNotification] NVARCHAR(10) NOT NULL DEFAULT '#fff4ff8c', 
    [ColorUpdatedItem] NVARCHAR(5) NOT NULL DEFAULT '#FFDEDEDE', 
    [ColorBalancedItem] NVARCHAR(5) NOT NULL DEFAULT '#ff94ffb6', 
    [ColorDeptorItem] NVARCHAR(5) NOT NULL DEFAULT '#ffff9c7a', 
    [ColorCreditorItem] NVARCHAR(5) NOT NULL DEFAULT '#ff7ad3ff', 
    [ColorInactiveItem] NVARCHAR(5) NOT NULL DEFAULT '#ffc9c9c9', 
    [ColorArchiveItem] NVARCHAR(5) NOT NULL DEFAULT '#ffffe0a3', 
    [ColorDeletedItem] NVARCHAR(5) NOT NULL DEFAULT '#ffff6b6b', 
    [ColorNegativeProfit] NVARCHAR(5) NOT NULL DEFAULT '#ffffadad',
    [ColorPositiveItem] NVARCHAR(5) NOT NULL DEFAULT '#ff7ad3ff', 
    [ColorNegativeItem] NVARCHAR(5) NOT NULL DEFAULT '#ffff9c7a',
    [DataGridFontSize] SMALLINT NOT NULL DEFAULT 12, 
    [ChequeListPageSize] INT NOT NULL DEFAULT 50, 
    [ChequeListQueryOrderType] NVARCHAR(5) NOT NULL DEFAULT 'DESC', 
    [ChequeNotifyDays] SMALLINT NOT NULL DEFAULT 2, 
    [ChequeNotify] BIT NOT NULL DEFAULT 1, 
    [InvoicePageSize] INT NOT NULL DEFAULT 50, 
    [InvoiceListQueryOrderType] NVARCHAR(5) NOT NULL DEFAULT 'DESC', 
    [InvoiceDetailQueryOrderType] NVARCHAR(5) NOT NULL DEFAULT 'DESC', 
    [TransactionPageSize] INT NOT NULL DEFAULT 50, 
    [TransactionListQueryOrderType] NVARCHAR(5) NOT NULL DEFAULT 'DESC', 

    CONSTRAINT [PK_UserSettings] PRIMARY KEY ([Username]), 
)